import { Job, ExperienceLevel, JobType } from '@/interfaces';

// Job Categories
export const JOB_CATEGORIES = [
  'All Categories',
  'Software Development',
  'Data Science',
  'Design',
  'Marketing',
  'Product Management',
  'Sales',
  'Customer Support',
  'Human Resources',
  'Finance',
  'Operations',
  'Engineering',
  'Quality Assurance',
  'DevOps',
  'Security',
] as const;

// Locations
export const LOCATIONS = [
  'All Locations',
  'Remote',
  'New York, NY',
  'San Francisco, CA',
  'Los Angeles, CA',
  'Chicago, IL',
  'Austin, TX',
  'Seattle, WA',
  'Boston, MA',
  'Denver, CO',
  'Atlanta, GA',
  'London, UK',
  'Berlin, Germany',
  'Toronto, Canada',
  'Sydney, Australia',
  'Singapore',
] as const;

// Experience Levels
export const EXPERIENCE_LEVELS: ExperienceLevel[] = [
  'Entry-Level',
  'Mid-Level',
  'Senior',
  'Lead',
];

// Job Types
export const JOB_TYPES: JobType[] = [
  'Full-time',
  'Part-time',
  'Contract',
  'Internship',
];

// Mock Job Data
export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp Solutions',
    location: 'San Francisco, CA',
    category: 'Software Development',
    experienceLevel: 'Senior',
    type: 'Full-time',
    salary: {
      min: 120000,
      max: 180000,
      currency: 'USD',
    },
    description: 'We are seeking an experienced Frontend Developer to join our dynamic team. You will be responsible for building scalable, responsive web applications using modern JavaScript frameworks.',
    requirements: [
      '5+ years of experience with React, Vue, or Angular',
      'Strong understanding of HTML5, CSS3, and JavaScript ES6+',
      'Experience with state management (Redux, Context API)',
      'Proficiency in responsive design and accessibility standards',
      'Experience with TypeScript',
      'Strong problem-solving and communication skills',
    ],
    responsibilities: [
      'Develop and maintain responsive web applications',
      'Collaborate with designers and backend developers',
      'Write clean, maintainable, and testable code',
      'Participate in code reviews and provide constructive feedback',
      'Optimize applications for maximum speed and scalability',
    ],
    benefits: [
      'Competitive salary and equity',
      'Health, dental, and vision insurance',
      '401(k) matching',
      'Flexible work hours',
      'Professional development budget',
    ],
    postedDate: '2025-11-15',
    applicationDeadline: '2025-12-31',
    remote: false,
  },
  {
    id: '2',
    title: 'Full Stack Engineer',
    company: 'StartupHub Inc',
    location: 'Remote',
    category: 'Software Development',
    experienceLevel: 'Mid-Level',
    type: 'Full-time',
    salary: {
      min: 90000,
      max: 130000,
      currency: 'USD',
    },
    description: 'Join our fast-growing startup as a Full Stack Engineer. You will work on exciting projects that impact millions of users worldwide.',
    requirements: [
      '3+ years of full stack development experience',
      'Proficiency in React and Node.js',
      'Experience with PostgreSQL or MongoDB',
      'Understanding of RESTful APIs and GraphQL',
      'Familiarity with AWS or similar cloud platforms',
      'Strong analytical and problem-solving abilities',
    ],
    responsibilities: [
      'Build and maintain full stack applications',
      'Design and implement APIs',
      'Collaborate with cross-functional teams',
      'Ensure application performance and security',
      'Participate in agile development processes',
    ],
    benefits: [
      'Remote-first culture',
      'Stock options',
      'Unlimited PTO',
      'Home office stipend',
      'Learning and development opportunities',
    ],
    postedDate: '2025-11-20',
    applicationDeadline: '2026-01-15',
    remote: true,
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'Creative Studios',
    location: 'New York, NY',
    category: 'Design',
    experienceLevel: 'Mid-Level',
    type: 'Full-time',
    salary: {
      min: 80000,
      max: 110000,
      currency: 'USD',
    },
    description: 'We are looking for a talented UX/UI Designer to create beautiful, intuitive user experiences for our digital products.',
    requirements: [
      '3+ years of UX/UI design experience',
      'Proficiency in Figma, Sketch, or Adobe XD',
      'Strong portfolio demonstrating design thinking',
      'Understanding of user research and testing methods',
      'Knowledge of accessibility standards (WCAG)',
      'Excellent communication skills',
    ],
    responsibilities: [
      'Create wireframes, prototypes, and high-fidelity designs',
      'Conduct user research and usability testing',
      'Collaborate with developers to implement designs',
      'Maintain and evolve design systems',
      'Present design concepts to stakeholders',
    ],
    benefits: [
      'Competitive compensation',
      'Health and wellness benefits',
      'Creative workspace',
      'Professional growth opportunities',
      'Team building events',
    ],
    postedDate: '2025-11-18',
    remote: false,
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'DataTech Analytics',
    location: 'Boston, MA',
    category: 'Data Science',
    experienceLevel: 'Senior',
    type: 'Full-time',
    salary: {
      min: 130000,
      max: 170000,
      currency: 'USD',
    },
    description: 'Join our data science team to build predictive models and derive insights from large datasets.',
    requirements: [
      '5+ years of experience in data science or machine learning',
      'Strong programming skills in Python and R',
      'Experience with ML frameworks (TensorFlow, PyTorch, scikit-learn)',
      'Proficiency in SQL and data visualization tools',
      'Masters or PhD in Computer Science, Statistics, or related field',
      'Strong statistical analysis skills',
    ],
    responsibilities: [
      'Develop and deploy machine learning models',
      'Analyze complex datasets to extract insights',
      'Collaborate with engineering and product teams',
      'Present findings to technical and non-technical audiences',
      'Stay current with latest ML/AI advancements',
    ],
    benefits: [
      'Excellent compensation package',
      'Full health benefits',
      'Research time for personal projects',
      'Conference attendance',
      'Collaborative environment',
    ],
    postedDate: '2025-11-10',
    applicationDeadline: '2025-12-20',
    remote: false,
  },
  {
    id: '5',
    title: 'Junior Frontend Developer',
    company: 'WebFlow Agency',
    location: 'Austin, TX',
    category: 'Software Development',
    experienceLevel: 'Entry-Level',
    type: 'Full-time',
    salary: {
      min: 60000,
      max: 80000,
      currency: 'USD',
    },
    description: 'Perfect opportunity for a junior developer to grow their skills in a supportive environment.',
    requirements: [
      '1-2 years of frontend development experience',
      'Knowledge of HTML, CSS, and JavaScript',
      'Familiarity with React or Vue',
      'Understanding of responsive design principles',
      'Eagerness to learn and grow',
      'Good communication skills',
    ],
    responsibilities: [
      'Assist in developing web applications',
      'Write clean, well-documented code',
      'Participate in team meetings and code reviews',
      'Learn from senior developers',
      'Fix bugs and implement new features',
    ],
    benefits: [
      'Mentorship program',
      'Health insurance',
      'Learning budget',
      'Flexible hours',
      'Career growth opportunities',
    ],
    postedDate: '2025-11-22',
    remote: false,
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'CloudScale Systems',
    location: 'Remote',
    category: 'DevOps',
    experienceLevel: 'Mid-Level',
    type: 'Full-time',
    salary: {
      min: 110000,
      max: 150000,
      currency: 'USD',
    },
    description: 'Looking for a DevOps Engineer to manage our cloud infrastructure and CI/CD pipelines.',
    requirements: [
      '3+ years of DevOps experience',
      'Strong knowledge of AWS, Azure, or GCP',
      'Experience with Docker and Kubernetes',
      'Proficiency in scripting (Python, Bash)',
      'Understanding of CI/CD tools (Jenkins, GitLab CI)',
      'Experience with infrastructure as code (Terraform, CloudFormation)',
    ],
    responsibilities: [
      'Manage cloud infrastructure',
      'Build and maintain CI/CD pipelines',
      'Monitor system performance and reliability',
      'Implement security best practices',
      'Collaborate with development teams',
    ],
    benefits: [
      'Remote work flexibility',
      'Comprehensive benefits',
      '401(k) with matching',
      'Professional certifications',
      'Work-life balance',
    ],
    postedDate: '2025-11-25',
    remote: true,
  },
  {
    id: '7',
    title: 'Product Manager',
    company: 'InnovateTech',
    location: 'Seattle, WA',
    category: 'Product Management',
    experienceLevel: 'Senior',
    type: 'Full-time',
    salary: {
      min: 140000,
      max: 190000,
      currency: 'USD',
    },
    description: 'Lead product strategy and execution for our flagship products.',
    requirements: [
      '5+ years of product management experience',
      'Strong analytical and data-driven approach',
      'Experience with agile methodologies',
      'Excellent communication and leadership skills',
      'Technical background preferred',
      'MBA or equivalent experience',
    ],
    responsibilities: [
      'Define product vision and strategy',
      'Manage product roadmap',
      'Work with engineering, design, and marketing teams',
      'Conduct market research and competitive analysis',
      'Make data-driven product decisions',
    ],
    benefits: [
      'Competitive salary and equity',
      'Comprehensive health benefits',
      'Retirement planning',
      'Leadership development programs',
      'Generous PTO',
    ],
    postedDate: '2025-11-12',
    remote: false,
  },
  {
    id: '8',
    title: 'Marketing Intern',
    company: 'GrowthHacker Media',
    location: 'Los Angeles, CA',
    category: 'Marketing',
    experienceLevel: 'Entry-Level',
    type: 'Internship',
    salary: {
      min: 20,
      max: 25,
      currency: 'USD',
    },
    description: 'Gain hands-on experience in digital marketing and growth strategies.',
    requirements: [
      'Currently pursuing or recently completed degree in Marketing',
      'Strong written and verbal communication skills',
      'Familiarity with social media platforms',
      'Basic knowledge of analytics tools',
      'Creative mindset',
      'Ability to work 20-30 hours per week',
    ],
    responsibilities: [
      'Assist with social media management',
      'Create content for marketing campaigns',
      'Analyze marketing metrics',
      'Support event planning',
      'Research industry trends',
    ],
    benefits: [
      'Hourly compensation',
      'Real-world experience',
      'Mentorship opportunities',
      'Potential for full-time offer',
      'Flexible schedule',
    ],
    postedDate: '2025-11-28',
    applicationDeadline: '2026-01-05',
    remote: false,
  },
  {
    id: '9',
    title: 'QA Engineer',
    company: 'QualityFirst Software',
    location: 'Chicago, IL',
    category: 'Quality Assurance',
    experienceLevel: 'Mid-Level',
    type: 'Full-time',
    salary: {
      min: 85000,
      max: 115000,
      currency: 'USD',
    },
    description: 'Ensure the quality and reliability of our software products through comprehensive testing.',
    requirements: [
      '3+ years of QA experience',
      'Experience with automated testing tools (Selenium, Cypress)',
      'Knowledge of testing methodologies',
      'Proficiency in at least one programming language',
      'Understanding of CI/CD processes',
      'Strong attention to detail',
    ],
    responsibilities: [
      'Design and execute test plans',
      'Develop automated test scripts',
      'Identify and document bugs',
      'Collaborate with development teams',
      'Ensure quality standards are met',
    ],
    benefits: [
      'Competitive salary',
      'Health and wellness benefits',
      'Professional development',
      'Hybrid work model',
      'Collaborative culture',
    ],
    postedDate: '2025-11-17',
    remote: false,
  },
  {
    id: '10',
    title: 'Backend Engineer - Node.js',
    company: 'API Masters',
    location: 'Remote',
    category: 'Software Development',
    experienceLevel: 'Mid-Level',
    type: 'Contract',
    salary: {
      min: 80,
      max: 120,
      currency: 'USD',
    },
    description: '6-month contract position for an experienced Node.js developer to build scalable APIs.',
    requirements: [
      '4+ years of backend development experience',
      'Expert knowledge of Node.js and Express',
      'Experience with microservices architecture',
      'Proficiency in database design (SQL and NoSQL)',
      'Understanding of security best practices',
      'Experience with message queues (RabbitMQ, Kafka)',
    ],
    responsibilities: [
      'Design and implement RESTful APIs',
      'Optimize database queries',
      'Write comprehensive tests',
      'Document API specifications',
      'Collaborate with frontend team',
    ],
    benefits: [
      'Hourly rate compensation',
      'Fully remote position',
      'Flexible schedule',
      'Opportunity for extension',
      'Work with modern tech stack',
    ],
    postedDate: '2025-11-26',
    applicationDeadline: '2025-12-15',
    remote: true,
  },
];

// API Configuration
export const API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_API_URL || 'https://api.jobboard.example.com',
  ENDPOINTS: {
    JOBS: '/api/jobs',
    APPLY: '/api/applications',
  },
  TIMEOUT: 10000,
};

// Filter Default Values
export const DEFAULT_FILTERS = {
  category: 'All Categories',
  location: 'All Locations',
  experienceLevel: '',
  jobType: '',
  searchQuery: '',
  remoteOnly: false,
};

// Form Validation Messages
export const VALIDATION_MESSAGES = {
  REQUIRED: 'This field is required',
  INVALID_EMAIL: 'Please enter a valid email address',
  INVALID_PHONE: 'Please enter a valid phone number',
  MIN_LENGTH: (min: number) => `Must be at least ${min} characters`,
  MAX_LENGTH: (max: number) => `Must be no more than ${max} characters`,
  MIN_VALUE: (min: number) => `Must be at least ${min}`,
};

// Loading Messages
export const LOADING_MESSAGES = {
  FETCHING_JOBS: 'Loading job listings...',
  SUBMITTING_APPLICATION: 'Submitting your application...',
};

// Error Messages
export const ERROR_MESSAGES = {
  FETCH_FAILED: 'Failed to load job listings. Please try again later.',
  SUBMIT_FAILED: 'Failed to submit application. Please try again.',
  NETWORK_ERROR: 'Network error. Please check your connection.',
  GENERIC_ERROR: 'Something went wrong. Please try again.',
};
